### ISSUE TITLE
Mekanism crashes with Speedster Heros [1.12.2]

### ISSUE THREAD

**Issue by Janik0000** [mekanism/Mekanism#6182]
#### Issue description:
Game Crashes as soon as you try to start the game with both of the mods installed

#### Steps to reproduce:
1. Install Mekanism, Speedster Heros and Lucraft: Core (lib for Speedster Heros)
2. Try to start the Game
3. Watch it Crashing

#### Versions:
**Game:1.12.2
**Forge:14.23.5.2854
**Mekanism:every version
**Speedster heros:2.1.4

**Comment by pupnewfster** [comment]
We are no longer developing for 1.12. If you provide the crash log we may be able to give you some idea what to attempt to do but as it stands with the lack of information and it being for a no longer developed version I am going ahead and closing this.

**Comment by Gryffen1971** [comment]
@pupnewfster , As a long time user of Mekanism in my MC1.12.2 pack build. I have not run into this problem.
I had to help out. So, i created a Test Profile with just the mods listed above and ran 3 tests.

On the 1st Test Game Crashed. I have a link to the crash report;
[](https://pastebin.com/BLUUZhzT)

On the 2nd Test I removed the Speedster heros 2.1.4 and Dependency the Game Loaded.

On the 3rd Test I added back in Lucraft: Core only and the Game Crashed.

With the Lucraft:  Core Mod loaded it is causing Mekanism to throw a "java.lang.NoClassDefFoundError: mekanism/common/entity/EntityRobit" exception. When the mod is not there then the exception is not thrown. 

When looking further done the crash log Lucraft:  Core is causing Exceptions for Mods that are not even installed in this test profile. So, i believe that Lucraft:  Core is causing Exceptions to be thrown with mods that it is not compatible with let alone mods that are not even installed.

I know the 1.12.2 versions of Mekanism are not supported but, i had to help in anyway i could to help  out @Janik0000 with there problem.

Hope what i done helped.

**Comment by pupnewfster** [comment]
https://gitlab.com/threetag/legacy/LucraftCore/-/issues/17

**Comment by thiakil** [comment]
Thanks for verifying @Gryffen1971 

Basically they're bundling _part_ of Galacticraft's API, so Forge thinks "OK, Mekanism has said it needs GC's API, and I'm seeing here that's installed, nothing to do here" - where it would otherwise strip out the crashing part because it's not present.

I've mentioned it on their issue tracker, so hopefully it gets fixed in the future - there's not much we could do even if we were still working on 1.12

**Comment by Gryffen1971** [comment]
Your Welcome @pupnewfster and @thiakil 
I figured it was doing that. It has taken me along time to understand the crash log.
Thanks for confirming what i thought.
