### ISSUE TITLE
Crash on MC 1.6.2

### ISSUE THREAD

**Issue by calclavia** [mekanism/Mekanism#191]
You claimed your latest build works with 1.6?

java.lang.NoSuchMethodError: net.minecraftforge.common.EnumHelper.addToolMaterial(Ljava/lang/String;IIFII)Lnet/minecraft/item/EnumToolMaterial;     at mekanism.tools.common.MekanismTools.<clinit>(MekanismTools.java:39)  at java.lang.Class.forName0(Native Method)  at java.lang.Class.forName(Unknown Source)  at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:457)   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)  at java.lang.reflect.Method.invoke(Unknown Source)  at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)  at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)  at com.google.common.eventbus.EventBus.post(EventBus.java:267)  at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:194)  at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:174)    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)  at java.lang.reflect.Method.invoke(Unknown Source)  at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)  at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)  at com.google.common.eventbus.EventBus.post(EventBus.java:267)  at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:105)   at cpw.mods.fml.common.Loader.loadMods(Loader.java:510)     at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:182)    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:470)  at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:796)  at net.minecraft.client.main.Main.main(SourceFile:101)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)  at java.lang.reflect.Method.invoke(Unknown Source)  at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)    at net.minecraft.launchwrapper.Launch.main(Launch.java:18)
